### ISSUE TITLE
Manually upload linux32 packages?

### ISSUE THREAD

**Issue by krischer** [conda-forge/obspy-feedstock#12]
Hi all,

we manually build linux32 packages (https://anaconda.org/obspy/obspy/files?version=1.0.3). Is there a possibility to manually upload them to the conda-forge anaconda channel or do you disallow that due to security concerns/other issues?

CC: @conda-forge/core 

Thanks!

**Comment by ocefpaf** [comment]
We do have "some" manual upload policies in place: https://github.com/conda-forge/conda-forge-enhancement-proposals/pull/5

However, I am afraid that we would need to upload a bunch of packages to satisfy the dependencies. How vital are these linux32 builds to you?

**Comment by krischer** [comment]
Not very vital - its more a nice to have thing. Most people with linux32 will have some kind of package manager for which we also have packages.

Why would you need to upload a couple of packages to satisfy the dependencies? I built these in a Docker container with only the default channel being active.

**Comment by ocefpaf** [comment]
> Why would you need to upload a couple of packages to satisfy the dependencies?

In order to use the rest of the conda-forge packages that are consistent with the recipe here.

> I built these in a Docker container with only the default channel being active.

Then I am guessing you made a few tweaks to the recipe, right?

**Comment by krischer** [comment]
No - no actual changes necessary (I only had to comment out the special handling of the icu packages but that issue maybe actually got fixed in the meanwhile) - the used file is this one: https://github.com/obspy/obspy/blob/master/misc/installer/anaconda/obspy/meta.yaml (but it is, aside the commented icu lines, identical to the conda-forge one).

All the other packages are also available in the default channel so conda should be smart enough to pick some from conda-forge if available and the rest from the default channel. Or am I missing something?

**Comment by ocefpaf** [comment]
> I only had to comment out the special handling of the icu packages but that issue maybe actually got fixed in the meanwhile

That was my only concern. Since there are no `linux32` packages in conda-forge that should be OK.

I would put a request for a manual upload in https://conda-forge.hackpad.com/conda-forge-meetings-2YkV96cvxPG so the other members of @conda-forge/core  can discuss and make a decision on this.

**Comment by krischer** [comment]
Done. It would be useful if there could be some automated way. The burden would be too large for you if people would have to ask you each time they update a package. Thus please only discuss a long term solution - it is not that crucial for us.

**Comment by megies** [comment]
> The burden would be too large for you if people would have to ask you each time they update a package

I tend to agree. Although I already saw some confusion about packages from our old `obspy` channel vs. `conda-forge` nowadays and keeping two strands alive (our own channel only for Linux32) will keep some potential confusion alive --  I think we should leave it as is right now. It would mean too much additional work for you guys.

**Comment by megies** [comment]
I think we don't really care about 32bit anymore, thus closing this one.
