### ISSUE TITLE
Move build obspy-1.1.1-*_0 to broken

### ISSUE THREAD

**Issue by megies** [conda-forge/obspy-feedstock#28]
Hi @conda-forge/core,

Please move the following build of my package `obspy` from ``main`` to ``broken`` on the conda-forge channel on anaconda.org:

`obspy-1.1.1-*_0.tar.bz2`

### Reason

Recent numpy version `1.17` breaks our package on build `obspy-1.1.1-*_0` due to removal of `numpy.fft.fftpack`. We have build number `1` with appropriate pinning for numpy already in `conda-forge`, replacing the old build with correct pinning (see #26, obspy/obspy#2434).

### Complete list of affected files

This is the list of files that should be moved to ``broken``:

```
linux-64/obspy-1.1.1-py27h3010b51_0.tar.bz2
linux-64/obspy-1.1.1-py36h3010b51_0.tar.bz2
linux-64/obspy-1.1.1-py37h3010b51_0.tar.bz2
osx-64/obspy-1.1.1-py27h917ab60_0.tar.bz2
osx-64/obspy-1.1.1-py36h917ab60_0.tar.bz2
osx-64/obspy-1.1.1-py37h917ab60_0.tar.bz2
win-64/obspy-1.1.1-py27hc997a72_0.tar.bz2
win-64/obspy-1.1.1-py36h452e1ab_0.tar.bz2
win-64/obspy-1.1.1-py37h452e1ab_0.tar.bz2
```

CC @krischer @mhearne-usgs

**Comment by ocefpaf** [comment]
Check https://anaconda.org/conda-forge/obspy/files?version=1.1.1 and let me know if we got all of them.

**Comment by megies** [comment]
Yes, thanks very much @ocefpaf!

**Comment by megies** [comment]
Jut a thought.. I guess for cases like these, it could help to have a "build number" filter as well.

..or a regex matching for filename like..
`https://anaconda.org/conda-forge/obspy/files?version=1.1.1&name=*_0.tar.bz2`

Then people could (in many/most cases) provide a link that matches all packages that needs changing.

**Comment by ocefpaf** [comment]
> Jut a thought.. I guess for cases like these, it could help to have a "build number" filter as well.

That is a feature request for `anaconda.org`.
